---
title: "Analysis on MovieLens dataset"
date: 10/07/2018
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(resample)

theme_set(theme_bw())
```

```{r, warning=FALSE}
readr::read_csv(here::here("data/movies.csv"),
                progress = FALSE,
                col_types = cols(
                      movieId = col_integer(),
                      title = col_character(),
                      genres = col_character()
                    )) %>% 
  group_by(movieId) %>%
  mutate(year = as.numeric(sub("\\).*", "",sub(".*\\(", "", title))),
         num_genres = length(as.list(strsplit(genres,'|',fixed = TRUE))[[1]]),
         homogeneous = num_genres == 1) %>% 
  na.omit() %>%
  ungroup() -> movies

readr::read_csv(here::here("data/ratings.csv"),
                progress = FALSE,
                col_types = cols(
                userId = col_integer(),
                movieId = col_integer(),
                rating = col_double(),
                timestamp = col_integer()
                )) %>%
  na.omit() -> ratings

dplyr::inner_join(
  movies,
  ratings,
  by="movieId") -> data

data %>%
  glimpse()

```

```{r}
data %>%
  ggplot(aes(year)) +
  geom_bar()
```

```{r}
data %>%
  ggplot(aes(num_genres)) +
  geom_bar()
```


```{r}
data %>%
  ggplot(aes(rating, 
             y=..prop..)) +
  geom_bar() + 
  facet_wrap(~ homogeneous) +
  labs(x="Movie Rating",
       y="Relative Frequency")
```


```{r}
data %>%
  group_by(movieId,
           title,
           year,
           num_genres,
           homogeneous) %>%
  summarise(median_rating = median(rating),
            well_rated = median_rating > 3.5) -> data
```

